services:
  - type: web
    name: texas-holdem-poker
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: texas-holdem-poker
          property: port
